---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get install libxml2-utils

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build the grammar file
        run: |
          bundle exec rake build | xmllint --format - > grammar_custom.xml

      - name: Rename LICENSE
        run: |
          cp LICENSE LICENSE.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        # https://github.com/softprops/action-gh-release
        with:
          files: |
            grammar_custom.xml
            LICENSE.txt
